# Generated by Django 3.1.3 on 2020-11-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='auther',
            new_name='author',
        ),
    ]
