# Generated by Django 3.1.3 on 2020-11-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201126_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
